### ISSUE TITLE
Hide core variables from Lua itself and Minetest's Lua API

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/qa_block#13]
In the globals tab, there are many variables which come from the core APIs.

I mean global Lua variables like:
* `_G`
* `_VERSION`
* `string`
* `math`
* `xpcall`
* `dofile`

And global Minetest variables like:
* `minetest`
* `core`
* `dump`
* `dump2`

It is not really useful to have these in the list as they just clutter the view IMO. I am mostly interested in the globals which come from mods.

I like to have a checkbox which allows me to filter out anything which comes from the core APIs (either Lua or Minetest).

Activating the checkbox should filter out:

* Functions which have “=[C]” as the source (this automatically means they come either from Lua or Minetest)
* Functions in the path of `builtin` (more Lua API stuff)
* For the remaining variables which are not functions:
   * All top-level globals defined in http://www.lua.org/manual/5.1/ (e.g. `_VERSION`)
   * All top-level globals defined in `lua_api.txt` (e.g. `minetest`, `core`)

The first 2 checks can be done automatically. The non-function variables can be filtered out by a hard-coded list.

**Comment by bell07** [comment]
Unsure if this is in scope of globals browser.
1. A checkbox already exists to hide ALL functions because not browsable/viewable
2. To hide minetest/core: my most used use-case is to show into minetest.registered_???
3. In most cases you search for a specific Lua global by name, the search field can be used for this case
(minet<enter/select minetest>nodes<enter/select registered_nodes>dirt<enter/select default:dirt_with_dry_grass>

If you search for a way to find the "leaked" globals, the global_variables.lua check still exists that does filter out all the builtin globals
